title: Shuang Li's Homepage
page-top-title: Shuang Li
top-section-bg-text: Computer Science
home-subtitle: Shuang Li&ensp;|&ensp;李爽11
copyright-text: '&copy; Shuang Li 2023-2024. All Rights Reserved.'
